{% set name = "pydeck" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f74475ae637951d63f2ee58326757f8d4f9cd9f2a457cf42950715003e2cb605

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python >=3.8
    - ipykernel
    - ipython
    - jupyter>=1.0.0
    - jinja2>=2.10.1
    - traitlets>=4.3.2
    - numpy >=1.16.4
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.8
    - ipykernel>=5.1.2
    - ipywidgets>=7,<8
    - jinja2>=2.10.1
    - traitlets>=4.3.2
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pydeck
    - pydeck.bindings
    - pydeck.data_utils
    - pydeck.io
    - pydeck.nbextension
    - pydeck.widget

about:
  home: https://github.com/visgl/deck.gl/tree/master/bindings/pydeck
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Widget for deck.gl maps
  doc_url: https://deckgl.readthedocs.io
  dev_url: https://github.com/visgl/deck.gl/tree/master/bindings/pydeck

extra:
  recipe-maintainers:
    - ajduberstein
    - Jesus89
