{% set name = "pydeck" %}
{% set version = "0.8.0b4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 103f303ef0a8f18edb10444d8136b901514779e84e340a86218e67427559e6d2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - ipykernel
    - ipython
    - jinja2
    - pip
    - traitlets
    - numpy >=1.16.4
  run:
    - python >=3.7
    - ipykernel
    - ipywidgets
    - jinja2
    - traitlets
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pydeck
    - pydeck.bindings
    - pydeck.data_utils
    - pydeck.io
    - pydeck.nbextension
    - pydeck.widget

about:
  home: https://github.com/visgl/deck.gl/tree/master/bindings/pydeck
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Widget for deck.gl maps
  doc_url: https://deckgl.readthedocs.io
  dev_url: https://github.com/visgl/deck.gl/tree/master/bindings/pydeck

extra:
  recipe-maintainers:
    - ajduberstein
    - Jesus89
