{% set name = "pydeck" %}
{% set version = "0.9.1" %}
{% set python_min = python_min|default("3.8") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydeck-{{ version }}.tar.gz
  sha256: f74475ae637951d63f2ee58326757f8d4f9cd9f2a457cf42950715003e2cb605

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - jinja2 >=2.10.1
    - jupyter >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - jinja2 >=2.10.1
    - numpy >=1.16.4
  run_constrained:
    - ipykernel >=5.1.2
    - ipywidgets >=7,<8
    - traitlets >=4.3.2 

test:
  imports:
    - pydeck
    - pydeck.bindings
    - pydeck.data_utils
    - pydeck.io
    - pydeck.nbextension
    - pydeck.widget
  commands:
    - pip check
  requires:
    - python ={{ python_min }}
    - pip
    - ipykernel >=5.1.2
    - ipywidgets >=7,<8
    - traitlets >=4.3.2

about:
  home: https://github.com/visgl/deck.gl/tree/master/bindings/pydeck
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Widget for deck.gl maps
  doc_url: https://deckgl.readthedocs.io
  dev_url: https://github.com/visgl/deck.gl/tree/master/bindings/pydeck

extra:
  recipe-maintainers:
    - ajduberstein
    - Jesus89
    - rxm7706
