{% set name = "pydeck" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07edde833f7cfcef6749124351195aa7dcd24663d4909fd7898dbd0b6fbc01ec

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - ipykernel
    - ipython
    - jinja2
    - pip
    - traitlets
    - numpy >=1.16.4
  run:
    - python >={{ python_min }}
    - ipykernel
    - ipywidgets
    - jinja2
    - traitlets
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pydeck
    - pydeck.bindings
    - pydeck.data_utils
    - pydeck.io
    - pydeck.nbextension
    - pydeck.widget

about:
  home: https://github.com/visgl/deck.gl/tree/master/bindings/pydeck
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Widget for deck.gl maps
  doc_url: https://deckgl.readthedocs.io
  dev_url: https://github.com/visgl/deck.gl/tree/master/bindings/pydeck

extra:
  recipe-maintainers:
    - ajduberstein
    - Jesus89
